---
title: "Probability of passing exams"
author: "Javier Álvarez Liébana"
date: "22th of June 2021"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r ajustes, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```

```{r preparacion, message = FALSE}
rm(list = ls()) # borramos entorno
# setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # fijamos directorio
# Instalamos paquetes necesarios
repos <- "http://cran.us.r-project.org"
if(!require(ggplot2)) install.packages("ggplot2", repos = repos)
if(!require(latex2exp)) install.packages("latex2exp", repos = repos)
if(!require(tidyverse)) install.packages("tidyverse", repos = repos)
if(!require(lubridate)) install.packages("lubridate", repos = repos)
if(!require(ggthemes)) install.packages("ggthemes", repos = repos)
if(!require(patchwork)) install.packages("patchwork", repos = repos)
if(!require(colorspace)) install.packages("colorspace", repos = repos)
if(!require(calendR)) install.packages("calendR", repos = repos)
if(!require(patchwork)) install.packages("patchwork", repos = repos)
if(!require(here)) install.packages("here", repos = repos)
if(!require(glue)) install.packages("glue", repos = repos)
if(!require(pdftools)) install.packages("pdftools", repos = repos)
```

```{r tema-base-fuentes-plots}
# Fuentes para los gráficos
library(showtext)
font_add_google("Lobster Two", "lobstertwo")
font_add_google("Poppins", "poppins")
showtext_auto()

# Tema base
theme_set(theme_bw())
theme_update(
  # Fuentes y ajustes de la leyenda
  legend.text = element_text(size = 15, family = "poppins"),
  legend.title = element_text(face = "bold", size = 17,
                              family = "poppins"),
  # Fuentes de los textos
  text = element_text(family = "poppins", size = 15, color = "black"),
  # Fuentes y ajustes de título, subtítulo y caption
  plot.title = element_text(family = "poppins", size = 25,
                            face = "bold", color = "#2a475e"),
  plot.subtitle = element_text(family = "poppins", size = 15,
                               face = "bold", color = "black"),
  plot.caption = element_text(size = 15, family = "poppins"),
  # Fuentes y ajustes de los ejes
  axis.text = element_text(size = 15, color = "grey50",
                           family = "poppins"),
  axis.title = element_text(size = 19, family = "poppins"),
  axis.ticks = element_blank(), axis.line = element_line(colour = "grey50"),
  # Ajustes del grid
  rect = element_blank(), panel.grid = element_line(color = "#b4aea9"),
  panel.grid.minor = element_blank(),
  panel.grid.major.x = element_blank(),
  panel.grid.major.y = element_line(linetype = "dashed"),
  plot.background =
    element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
  # Márgenes
  plot.margin = # márgenes
    margin(t = 0.5, b = 0.5, r = 0.9, l = 0.9, "cm"))
```

```{r simulacion-oposiciones}
n_temas <- 71 # temas a elegir
n_bolas <- 5 # número de bolas en el examen
n_simul <- 1e4 # 10 000 simulaciones

set.seed(1234567) # Fijamos semilla para generar lo mismo

# Guardamos en temas_exito el número de simulaciones en las
# que nos hemos sabido 0, 1, 2, ..., n_bolas temas, y en
# temas_extraídos los n_bolas temas candidatos
# en cada simulación
temas_exito <- matrix(0, n_temas, n_bolas + 1)
for (i in 1:n_temas) {
  for (j in 1:n_simul) {
    temas_extraidos <- sample(1:n_temas, n_bolas, replace = FALSE)
    for (k in 0:n_bolas) {
      
      temas_exito[i, k + 1] <- temas_exito[i, k + 1] +
        (sum(temas_extraidos %in% 1:i) == k)
      
    }
  }
}
temas_exito <- temas_exito / n_simul # en %
```

```{r preproc-datos}
# Convertimos los datos a formato data.frame
temas_exito <- data.frame(temas_exito)
names(temas_exito) <-
  c("0 de los estudiados", "1 de los estudiados",
    "2 de los estudiados", "3 de los estudiados",
    "4 de los estudiados", "5 de los estudiados")

# Calculamos el acumulado: prob. de saber al menos X temas de los extraídos
temas_exito_acum <-
  data.frame(temas_exito[, 1], 1 - temas_exito[, 1],
             1 - rowSums(temas_exito[, 1:2]),
             1 - rowSums(temas_exito[, 1:3]),
             1 - rowSums(temas_exito[, 1:4]), temas_exito[, 6])
temas_exito_diff <- # Diferencia de probabilidad según estudiamos temas
  rbind(apply(temas_exito_acum, MARGIN = 2, diff), rep(0, 6))
names(temas_exito_acum) <- names(temas_exito_diff) <-
  c("0 de los estudiados", "al menos 1 de los estudiados",
    "al menos 2 de los estudiados", "al menos 3 de los estudiados",
    "al menos 4 de los estudiados", "5 de las estudiadas")

# Convertimos a data.frame
temas_exito <- data.frame("prob" = as.numeric(unlist(temas_exito)),
                          "aciertos" = as.factor(rep(0:5, each = 71)))
temas_exito_acum <- data.frame("prob" = as.numeric(unlist(temas_exito_acum)),
                               "aciertos" = as.factor(rep(0:5, each = 71)))
temas_exito_diff <- data.frame("prob" = as.numeric(unlist(temas_exito_diff)),
                               "aciertos" = as.factor(rep(0:5, each = 71)))
```

```{r fig1, fig.width = 13, fig.height = 8}
fig1 <- 
  ggplot(temas_exito,
         aes(x = rep(1:n_temas, n_bolas + 1), y = prob,
             color = aciertos)) +
  # Pintamos las curvas de probabilidades de saberse 0, 1, ... n 
  # temas del bombo en función de los temas estudiados
  geom_line(size = 3) + # Tamaño 3 de línea
  # Línea vertical para el número de temas a partir del cual
  # es más probable saberte 1 tema que ninguno
  geom_segment(aes(x = 11, y = 0, xend = 11, yend = 1),
               linetype = "dashed", size = 1.5, color = "#2a475e") +
  # Escala de colores Red-Yellow-Blue
  scale_color_brewer(palette = "RdYlBu") + 
  labs(x = "Nº de temas aprendidos", # Etiquetas de los ejes
       y = "Probabilidad de que suceda",
       title = glue("PROBABILIDAD DE SABER 0, 1, ..., {n_bolas} TEMAS\n",
                    "EN OPOSICIONES DE {n_temas} TEMAS ",
                    "(CON {n_bolas} BOLAS)"),
       subtitle =
         glue("Cálculos con {n_simul} simulaciones. ",
              "Gráfico: Javier Álvarez Liébana (@DadosDeLaplace)")) +
  # Escala y cortes en el eje y
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1),
                     labels = scales::label_percent()) +
  # Anotación indicando los temas necesarios para ser
  # más probable 1 que 0
  annotate(geom = "curve", x = 20, xend = 12,
           y = 0.65, yend = 0.45, color = "#2a475e",
           curvature = 0.5, size = 1.7,
           arrow = arrow(length = unit(3.1, "mm")))  +
  annotate(geom = "text", x = 21, y = 0.65,
           label = paste0("A partir de 11 temas, hay más\n",
                          "opciones de saberte una que\n",
                          "de no saberte ninguna"),
           hjust = "left", family = "lobstertwo", face = "bold",
           color = "#2a475e", size = 7)
fig1

# Exportamos
ruta <- here("plots", "#matesendomingo",
             "2021_06_22_PASSING_EXAMS", "fig1")
ggsave(glue("{ruta}.pdf"),
       width = 13, height = 8, device = cairo_pdf)
pdftools::pdf_convert(glue("{ruta}.pdf"), filenames = glue("{ruta}.png"),
                      format = "png", dpi = 300)
```

```{r fig2, fig.width = 13, fig.height = 8}
fig2 <- 
  ggplot(temas_exito_acum,
         # Probabilidades de saberse AL MENOS X
         aes(x = rep(1:n_temas, n_bolas + 1),
             y = prob, color = aciertos)) +
  geom_line(size = 3) +  # Tamaño 3 de línea
  # Líneas vertical para indicar hitos
  geom_segment(aes(x = 9, y = 0, xend = 9, yend = 1),
               linetype = "dashed",  size = 0.7, color = "#2a475e") +
  geom_segment(aes(x = 36, y = 0, xend = 36, yend = 1),
               linetype = "dashed",  size = 0.7, color = "#2a475e") +
  geom_segment(aes(x = 46, y = 0, xend = 46, yend = 1),
               linetype = "dashed",  size = 0.7, color = "#2a475e") +
  # Escala de colores Red-Yellow-Blue
  scale_color_brewer(palette = "RdYlBu") +
  labs(x = "Nº de temas aprendidos",
       y = "Probabilidad de que suceda") +
  # Escala y cortes en el eje y
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1),
                     labels = scales::label_percent()) +
  # Anotaciones
  annotate(geom = "curve", x = 16, xend = 8,
           y = 1.1, yend = 0.55, color = "#2a475e",
           curvature = 0.6, size = 1.2,
           arrow = arrow(length = unit(3.1, "mm")))  +
  annotate(geom = "text", x = 0.3, y = 1.2,
           label = paste0("A partir de 9 temas, hay más opciones\n",
                          "de saberte alguna que ninguna"),
           hjust = "left", family = "lobstertwo", face = "bold",
           color = "#2a475e", size = 7)  +
  annotate(geom = "curve", x = 57, xend = 37,
           y = 0.23, yend = 0.06, color = "#2a475e",
           curvature = 0.6, size = 1.2,
           arrow = arrow(length = unit(3.1, "mm")))  +
  annotate(geom = "text", x = 53, y = 0.12,
           label = paste0("A partir de 36 temas,\n",
                          "más opciones de saber\n",
                          "TODAS que ninguna"),
           hjust = "left", family = "lobstertwo", face = "bold",
           color = "#2a475e", size = 7)  +
  annotate(geom = "curve", x = 55, xend = 47,
           y = 1.11, yend = 1.01, color = "#2a475e",
           curvature = -0.4, size = 1.2,
           arrow = arrow(length = unit(3.1, "mm"))) +
  annotate(geom = "text", x = 47, y = 1.2,
           label = paste0("A partir de 46 temas, hay un\n",
                          "99.5% de saberte al menos una"),
           hjust = "left", family = "lobstertwo", face = "bold",
           color = "#2a475e", size = 7) +
  coord_cartesian(clip = "off")
fig2

# Exportamos
ruta <- here("plots", "#matesendomingo",
             "2021_06_22_PASSING_EXAMS", "fig2")
ggsave(glue("{ruta}.pdf"),
       width = 13, height = 8, device = cairo_pdf)
pdftools::pdf_convert(glue("{ruta}.pdf"), filenames = glue("{ruta}.png"),
                      format = "png", dpi = 300)
```
